### ISSUE TITLE
Status of event node is incorrect

### ISSUE THREAD

**Issue by eschava** [andreypopov/node-red-contrib-miio-roborock#10]
** Describe issue **
I always have the status  of event node same to:
Charging (202%)

** Screens / Logs **
Command node "get status" returns
```
[{"msg_ver":2,"msg_seq":501,"state":8,"battery":100,"clean_time":1217,"clean_area":21080000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":0,"fan_power":102,"dnd_enabled":0,"map_status":253,"is_locating":0,"lock_status":0,"water_box_mode":202,"water_box_carriage_status":0,"mop_forbidden_enable":0}]
```

**Comment by andreypopov** [comment]
what is vacuum model?

**Comment by Graefer** [comment]
Same here (Roborock S5 Max).

**Comment by eschava** [comment]
> what is vacuum model?

sorry, missed your question.
Same, S5 Max

**Comment by andreypopov** [comment]
please, test 2.0.2 release

![2020-09-04_13-02-38](https://user-images.githubusercontent.com/1624839/92227473-017edc00-eeaf-11ea-8bd6-2aa89f3339df.png)
