### ISSUE TITLE
Event list is empty

### ISSUE THREAD

**Issue by gkojtek** [andreypopov/node-red-contrib-miio-roborock#14]
The list is for Roborock S50, so I cannot listen for events.

![image](https://user-images.githubusercontent.com/25907703/85811102-660a1600-b75d-11ea-9df0-d9d80a1cb1d2.png)

**Hardware / Software**

- Raspberry Pi 4B
- Version of deconz gateway: [2.05.75 / 08/02/2020]
- Version of node-red-contrib-deconz: [1.1.14]

**Comment by SimplyRyan** [comment]
What version of node-red-contrib-miio-roborock are you using?

**Comment by gkojtek** [comment]
Hi! It's 1.2.0,

**Comment by SimplyRyan** [comment]
I don't get the blank event box on 1.2.0 with my S5 (S50). Can you try giving it a name and making sure its deployed?

**Comment by gkojtek** [comment]
Sorry for the late reply. I didn't know it had to be deployed to be able to see the list. Thanks!
