### ISSUE TITLE
Токен?

### ISSUE THREAD

**Issue by semikor** [andreypopov/node-red-contrib-miio-roborock#16]
Доброго времени суток!
Подскажите, пожалуйста! 
Есть Roborock S6 версия прошивки 3.5.8_2076 - будет этот плагин с ним работать?
Все облазил, но так и не понял, что такое "Токен", как он выглядит и где его взять?
Есть MI ID (10 цифр) из приложения MiHome, но с ним не работает.
Спасибо!

**Comment by andreypopov** [comment]
будет работать, @popov1988 в телеге, могу объяснить как его получить
