### ISSUE TITLE
Own Voice Pack instalation to S5 Max

### ISSUE THREAD

**Issue by S474N** [andreypopov/node-red-contrib-miio-roborock#18]
** Describe issue **
Cannot install own voicepack via OTA/Node-Red node. There is no response from vacuum cleaner.

** Your flow here **
Injection JSON:

```
{
    "method": "dnld_install_sound",
    "params": {
        "md5": "myMD5checksumOfFile",
        "sid": 1005,
        "url": "http://MyServerPath/FILE.pkg",
        "sver": 2
    },
    "id": 1794
}
```

** Screens / Logs **

** Hardware / Software **
- raspberry 4  
- version of deconz gateway: [2.05.80 / 14. 8. 2020]
- version of node-red-contrib-deconz: [1.2.0]
- Roborock: [S5 Max]

**Comment by andreypopov** [comment]
gen3 vacuums support only official voice packs

**Comment by andreypopov** [comment]
what is the error code? check with "get progress" command

**Comment by S474N** [comment]
Tested, and error code: 0. 

```
state: 3
error: 0

```
I think, that problem is, that new generation (third) voicepack must be signed with RSA from manufacturer.

**Comment by andreypopov** [comment]
you are right

**Comment by S474N** [comment]
So, now we can close this issue :D
