### ISSUE TITLE
NodeRed hangs and restarting in endless loop if vacuum not available

### ISSUE THREAD

**Issue by becmar39** [andreypopov/node-red-contrib-miio-roborock#19]
** Describe issue **
If Vacuum is not available NodeRed hangs and restarting in endless loop

** Your flow here **
Happens with each Command or Event Flow.

** Screens / Logs **
node-red.0 | 2020-09-23 08:52:53.337 | info | (2706) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
-- | -- | -- | --
node-red.0 | 2020-09-23 08:52:48.336 | info | (2706) node-red exited with 6
node-red.0 | 2020-09-23 08:52:47.069 | warn | (22221) Terminated (UNCAUGHT_EXCEPTION): Without reason
node-red.0 | 2020-09-23 08:52:46.004 | error | (22221) Error: Could not connect to device, handshake timeout at Timeout.handshakeTimeout.setTimeout [as _onTimeout] (/opt/iobroker/iobroker-data/node-red/node_modules/miio/lib/network.js:427:17)
node-red.0 | 2020-09-23 08:52:46.003 | error | (22221) unhandled promise rejection: Could not connect to device, handshake timeout
node-red.0 | 2020-09-23 08:52:45.997 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
node-red.0 | 2020-09-23 08:52:45.994 | warn | (2706) 23 Sep 08:52:45 - [warn] [miio-roborock-server:Wilma] Miio Roborock Error: Could not connect to device, handshake timeout
node-red.0 | 2020-09-23 08:52:43.170 | warn | (2706) 23 Sep 08:52:43 - [warn] Projekte inaktiviert: editorTheme.projects.enabled=false
node-red.0 | 2020-09-23 08:52:31.727 | info | (2706) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js

** Hardware / Software **
  - raspberry 4

**Comment by andreypopov** [comment]
please, give full log
"Error: Could not connect to device " - in a loop is okay

node-red version?

**Comment by becmar39** [comment]
> please, give full log
> "Error: Could not connect to device " - in a loop is okay
> 
> node-red version?

Running in iobroker NodeRed Adapter: 1.17.2,  NodeRed NPM Version 1.1.3

Where can I find the full Log? EventList is empty, I think because i only able to run in SafeMode. Only thing I see in IObroker is:


node-red.0 | 2020-09-23 09:08:44.116 | error | (22919) Error: Could not connect to device, handshake timeout at Timeout.handshakeTimeout.setTimeout [as _onTimeout] (/opt/iobroker/iobroker-data/node-red/node_modules/miio/lib/network.js:427:17)
-- | -- | -- | --
node-red.0 | 2020-09-23 09:08:44.115 | error | (22919) unhandled promise rejection: Could not connect to device, handshake timeout
node-red.0 | 2020-09-23 09:08:44.112 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch()

**Comment by andreypopov** [comment]
this error will not cause node-red crash
it is reconnect attempt

**Comment by becmar39** [comment]
When Iam deleting the Configuration Node everything works fine.
Can you give me the location of Logfiles you need, then iam able to send it.

**Comment by andreypopov** [comment]
journalctl -f -n  200 -u nodered -o cat

**Comment by becmar39** [comment]
Now I created again the ConfigurationNode, Deploy -> Crash.
Didnt find any messages with your command. I only can see the messages in iobroker listet in 1st post.

**Comment by becmar39** [comment]
Enabled Debug Output:


node-red.0 | 2020-09-23 10:10:34.081 | info | (25507) node-red exited with 6
-- | -- | -- | --
node-red.0 | 2020-09-23 10:10:33.484 | warn | (25558) Terminated (UNCAUGHT_EXCEPTION): Without reason
tankerkoenig.0 | 2020-09-23 10:10:31.688 | info | (1550) Reading data from tankerkoenig ...
node-red.0 | 2020-09-23 10:10:31.309 | error | (25558) Error: Could not connect to device, handshake timeout at Timeout.handshakeTimeout.setTimeout [as _onTimeout] (/opt/iobroker/iobroker-data/node-red/node_modules/miio/lib/network.js:427:17)
node-red.0 | 2020-09-23 10:10:31.308 | error | (25558) unhandled promise rejection: Could not connect to device, handshake timeout
node-red.0 | 2020-09-23 10:10:31.307 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
node-red.0 | 2020-09-23 10:10:28.949 | debug | (25558) statesDB connected
node-red.0 | 2020-09-23 10:10:28.947 | debug | (25558) States connected to redis: 127.0.0.1:9000
node-red.0 | 2020-09-23 10:10:31.305 | warn | (25507) 23 Sep 10:10:31 - [warn] [miio-roborock-server:Wilma] Miio Roborock Error: Could not connect to device, handshake timeout
node-red.0 | 2020-09-23 10:10:31.300 | debug | (25507) 23 Sep 10:10:31 - [info] [inject:Start Pegeldaten] Wiederholen = 900000
node-red.0 | 2020-09-23 10:10:31.284 | debug | (25507) 23 Sep 10:10:31 - [info] [inject:Start Wetterdaten] Wiederholen = 120000
node-red.0 | 2020-09-23 10:10:31.214 | debug | (25507) 23 Sep 10:10:31 - [info] Flows gestartet
node-red.0 | 2020-09-23 10:10:30.972 | debug | (25507) 23 Sep 10:10:30 - [info] [inject:368d976c.5a0d48] Wiederholen = 10000
node-red.0 | 2020-09-23 10:10:29.030 | debug | (25507) 23 Sep 10:10:29 - [info] Flows starten
node-red.0 | 2020-09-23 10:10:28.921 | debug | (25507) 23 Sep 10:10:28 - [info] Server wird jetzt auf http://127.0.0.1:1880/ ausgeführt.
node-red.0 | 2020-09-23 10:10:28.790 | debug | (25507) 23 Sep 10:10:28 - [info] Flow-Datei: /opt/iobroker/iobroker-data/node-red/flows.json
node-red.0 | 2020-09-23 10:10:28.786 | warn | (25507) 23 Sep 10:10:28 - [info] Benutzerverzeichnis: /opt/iobroker/iobroker-data/node-red/ 23 Sep 10:10:28 - [warn] Projekte inaktiviert: editorTheme.projects.enabled=false
node-red.0 | 2020-09-23 10:10:28.783 | debug | (25507) 23 Sep 10:10:28 - [info] Kontextspeicher: 'default' [ module=memory]
node-red.0 | 2020-09-23 10:10:28.779 | debug | (25507) 23 Sep 10:10:28 - [info] Einstellungsdatei: /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-09-23 10:10:27.994 | debug | (25507) 23 Sep 10:10:27 - [info] Dashboard version 2.23.2 started at /ui
node-red.0 | 2020-09-23 10:10:25.759 | debug | (25507) 23 Sep 10:10:25 - [info] Polymer started at /polymer
node-red.0 | 2020-09-23 10:10:22.754 | debug | (25507) 23 Sep 10:10:22 - [info] Paletten-Nodes werden geladen
node-red.0 | 2020-09-23 10:10:20.445 | debug | (25507) 23 Sep 10:10:20 - [info] Linux 5.4.51-v7l+ arm LE
node-red.0 | 2020-09-23 10:10:20.444 | debug | (25507) 23 Sep 10:10:20 - [info] Node.js Version: v10.21.0
node-red.0 | 2020-09-23 10:10:20.443 | debug | (25507) 23 Sep 10:10:20 - [info] Node-RED Version: v1.1.3
node-red.0 | 2020-09-23 10:10:20.438 | debug | (25507) 23 Sep 10:10:20 - [info] Willkommen bei Node-RED! ===================

**Comment by andreypopov** [comment]
Node-red crashed due to exception, I dont see it in your logs.
### (25558) Terminated (UNCAUGHT_EXCEPTION): Without reason


My logs, I have to servers for vacuum, one of them with invalid ip:
![2020-09-23_11-20-08](https://user-images.githubusercontent.com/1624839/93986431-0688ca00-fd8f-11ea-980c-0dac5ebb49d2.png)

**Comment by becmar39** [comment]
Maybe a problem when running node-red as Iobroker Instance?

**Comment by andreypopov** [comment]
I will improve error messages and we will check.

**Comment by andreypopov** [comment]
added patch. please, check 2.1.1

**Comment by becmar39** [comment]
Sorry, same occurs. I updated to latest iobroker, NodeRed 2.2.2 an latest node-red-contrib-miio-roborock.
Now in Palette Manager I also see these errors:

![mii](https://user-images.githubusercontent.com/20090044/113614289-966ad300-9652-11eb-9fba-00ea378756db.png)

**Comment by andreypopov** [comment]
Please, test this version
+ node-red-contrib-miio-roborock@2.3.0

**Comment by becmar39** [comment]
Working. Thank you.
