### ISSUE TITLE
Koordinate doesn´t work

### ISSUE THREAD

**Issue by Blackei** [andreypopov/node-red-contrib-miio-roborock#2]
Hi,

i take the Koordinten from the Android app FloeVac and clientthe Area with App bevore, everything perfekt. Than i copy the Koordinte with long press on te Arrow and paste them into the Node...

[[26683,24465,30283,27665,1]] 

and the Robi want to clean everything......every Time ....

And how must be a coordinates for the Command "sed to Coordinates"? there i have only 2 Numbers?

**Comment by andreypopov** [comment]
Please, check my examples! Import them from node-red's UI.

[[26683,24465,30283,27665,1]] -  zone cleaning coordinates x1,y1,x2,y2, 1 means - times to clean
"send to coordinates" should have only 2 numbers
