### ISSUE TITLE
Xiaomi mop-p

### ISSUE THREAD

**Issue by michelefa1988** [andreypopov/node-red-contrib-miio-roborock#22]
Does anyone know if this addon will work on Xiaomi Robot  Vacum Mop-P?

I have attempted to connect it using this module but nothing ever happened, I just see the module initializing.

**Comment by andreypopov** [comment]
what is the model name? like: viomi.vacuum.v8

as I know xiaomi mop models will not work
I bought Xiaomi s1 - works fine

**Comment by michelefa1988** [comment]
The proper name if the device is "xiaomi mop-p" 

Is viomi.vacuum.v8 the name given to a software version or is it a version I can somehow dig out somewhere?

Thanks

**Comment by andreypopov** [comment]
sorry! node-red-contrib-miio-roborock will not support it
It works only though chineese cloud..
