### ISSUE TITLE
Cannot read property 'call' of undefined"

### ISSUE THREAD

**Issue by bj-tracer** [andreypopov/node-red-contrib-miio-roborock#23]
При попытке выполнить любую команду имеем ошибку из заголовка.
Буквально на днях все работало без проблем, пока не начал возиться с уборкой сегментов.

`[{
"id":"9ba893e6.e95e28",
"type":"inject",
"z":"3f7a9c78.8ea654",
"name":"",
"props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"On\":1}","payloadType":"json","x":160,"y":240,"wires":[["616f727.f06e50c"]]},

{
"id":"616f727.f06e50c",
"type":"miio-roborock-command",
"z":"3f7a9c78.8ea654",
"name":"Clean Kitchen",
"server":"11c2864f.0d623a",
"command_name":"►Старт",
"command":"app_start",
"commandType":"vacuum_cmd",
"payload":"arguments",
"payloadType":"vacuum_payload",
"coordinates":"[\n   [19500,22500,22200,26200,1]\n]","fan_speed":"","voice_pack":"5000","homekit_stop_to_dock":false,"x":400,"y":240,"wires":[["897c6636.d45b3"]]
},
{
"id":"897c6636.d45b3",
"type":"debug",
"z":"3f7a9c78.8ea654",
"name":"",
"active":true,
"tosidebar":true,
"console":false,
"tostatus":true,
"complete":"true",
"targetType":"full",
"statusVal":"payload",
"statusType":"auto",
"x":630,
"y":220,
"wires":[]
},

{"id":"11c2864f.0d623a",
"type":"miio-roborock-server",
"name":"config_name",
"ip":"robot_ip",
"token":"my_token",
"polling":"10"}]`
#данные робота удалены

<img width="273" alt="image" src="https://user-images.githubusercontent.com/50882159/106503917-4dbe5e80-64d7-11eb-8045-d2ac7eca6c29.png">

** Hardware / Software **
Synology NAS/ARM7
Node.jc 12
Node-Red 1.2.7

**Comment by andreypopov** [comment]
Не заметил проблемы пока, у меня как часы работает
IP статический у пылика? связь точно есть? какая модель пылесоса?
Я там еще объемный пример добавил, его можно импортировать, там есть уборка по комнатам.

**Comment by bj-tracer** [comment]
Адрес статический.
Нода roborock-miio работает без проблем, но там нет обработки методов уборки комнат.
Робот m1s. 3 дня назад команды из вашей ноды работали. Тестировал на поиске и отправке в док. Сломалось все, когда стал разбираться с комнатами - пробовал и просто в аргументе номер комнат добавлять, и через json передавать, и через функцию в payload. Результат один.
На текущий момент вообще ни на какие методы не отзывается.
Пробовал и ваш флоу - собственного с него и начались попытки научить хомкит запускать уборку в комнатах.

**Comment by andreypopov** [comment]
Если вообще никакие методы не отзываются - значит нет связи. 
сброс вай фая - обновляет токен

**Comment by bj-tracer** [comment]
Так другая нода работает.

**Comment by bj-tracer** [comment]
Все, вопрос решился.
По какой-то причине данная нода ушла в несознанку.
Удаление, ребут нод-ред и установка заново все решила.
Спасибо за участие!
