### ISSUE TITLE
How to get token when Roborock is registered to Roborock app

### ISSUE THREAD

**Issue by janky69** [andreypopov/node-red-contrib-miio-roborock#24]
Hi, i have Roborock S6 MaxV and if I reset WiFi setting I can get token with many tools. But if I add cleaner to Roborock App, token stop working... Exist some way to resolve this problem and stay by using Roborock App? Thank You very much!

**Comment by andreypopov** [comment]
I dont know, .. I can use mihome app + node-red

**Comment by janky69** [comment]
Yes, but MiHomeApp dont have some feature as Roborock. With Roborock i can use camera live view and photos of obstacles...

**Comment by Rob-for** [comment]
https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor

Works verry good!

**Comment by andreypopov** [comment]
It is crazy, but I implemented "catch cloud token" many months ago)forgot to finish it :))
![2021-03-05_16-33-55](https://user-images.githubusercontent.com/1624839/110122498-c2373680-7dd0-11eb-907b-cda58fbf2d9c.png)

**Comment by janky69** [comment]
Thank you for your answer, but I got Login incorrect. I mean so this working only with account for MiHome app, not for Roborock... Is ti true?

**Comment by andreypopov** [comment]
+ node-red-contrib-miio-roborock@2.1.1
miCloud parser added

**Comment by janky69** [comment]
Thank you for your great work! But it not resolve this issue. This tool (I mean) not work with Roborock App accounts. Cleaner can't share from roborock app to mihome app. Is some way to resolve how to use roborock app and node red? Thank you!

**Comment by TheNON75** [comment]
Hi All,

At this GitHub page there are some discussions about obtaining the token when the robot is connected to the roborock app.

[https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues?q=is%3Aissue+is%3Aopen++104](here)

There are 3 entries, one is a duplicate.

Some more recent and useful information can be found in #387. I hope it helps.
Apparently if the robot is used with the roborock app, it communicates differently and with different servers. I assume that is something that needs to be implemented....

![image](https://user-images.githubusercontent.com/60628305/120530119-7438cb80-c3dd-11eb-8a0d-6f1a213e6db9.jpeg)

**Comment by FezVrasta** [comment]
@andreypopov here you can find some node scripts to get the token and interface with the robot.

The API is being reverse engineered at https://github.com/humbertogontijo/homeassistant-roborock
