### ISSUE TITLE
After upgrade to 2.1.1 flows stopped due to missing node type error

### ISSUE THREAD

**Issue by DRazumovskiy** [andreypopov/node-red-contrib-miio-roborock#25]
Node-red reports that miio-roborock-server is missing. All flows stopped

![Roborock](https://user-images.githubusercontent.com/13840421/110200229-20116000-7e5d-11eb-9e1a-5792b012af75.png)

Node-red version 1.2.9

**Comment by ConBeeUser** [comment]
I have the exact same problem.
At the moment the only way to get node red back working again is to delete every node related to node-red-contrib-miio-roborock. 
I'm looking forward to getting this back working again :-) Would be awesome if I could get results of the room-id-query. 

Cheers, keep up your great work 👍

**Comment by andreypopov** [comment]
Please, check logs. 
I'd just updated - everything looks good.

![2021-03-08_12-52-24](https://user-images.githubusercontent.com/1624839/110304916-3100d380-800d-11eb-8089-6095dc0221dc.png)

**Comment by GinBook** [comment]
Still the same problem. It's broken.

**Comment by cp1983** [comment]
Was installing for the first time and got the same [Object] error.

Installed 2.0.8 instead and this works.

**Comment by andreypopov** [comment]
guys, I need logs... 
![2021-03-09_12-33-58](https://user-images.githubusercontent.com/1624839/110449939-c1095080-80d3-11eb-916e-3011657607c6.png)
I dont have errors.

**Comment by cp1983** [comment]
Not sure what kind of logs you want however was able to get this from journalctl.

See attached log file:
[nodered.txt](https://github.com/andreypopov/node-red-contrib-miio-roborock/files/6107540/nodered.txt)

**Comment by andreypopov** [comment]
try to upgrade node-red, you use old  v1.1.3, current is 1.2.9
also upgrade nodejs from v10 to v12 !


9 Mar 12:31:57 - [info] Node-RED version: v1.2.9
9 Mar 12:31:57 - [info] Node.js  version: v12.20.2

**Comment by cp1983** [comment]
Thanks. Upgrading Node.js to 12 did the trick.

**Comment by GinBook** [comment]
I'm confused.
I haven't changed anything and it's working.

**Comment by DRazumovskiy** [comment]
Issue risolved with the last fix. Works correctly on Node-Red 1.2.9 and node.js v10.24.0
