### ISSUE TITLE
Node red crashes when using this palette

### ISSUE THREAD

**Issue by pMRaptor** [andreypopov/node-red-contrib-miio-roborock#26]
** Describe issue **
Node red crashes after around 3 hour of uptime.  Any idea what is happening?

Encountered an error while controlling device
Error(2) was:
Call to device timed out
10 Mar 03:35:32 - [red] Uncaught Exception:
10 Mar 03:35:32 - Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (C:\Users\pkj\.node-red\node_modules\miio\lib\network.js:487:18)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)

** Hardware / Software **
  - Windows 10 PRO
  - 
  - version of node-red 1.2.9

**Comment by andreypopov** [comment]
nodejs version?

node-red-contrib-miio-roborock 2.1.2 ?

**Comment by pMRaptor** [comment]
I see that there are a new version. Will try to update.
Currently using:
Node js 14.16
node-red-contrib-miio-roborock 2.0.9

**Comment by andreypopov** [comment]
yes, try, new version has new error handling update

**Comment by pMRaptor** [comment]
Node red is stable after upgrade, so thanks for the nice work done there. But now i am having same issue as bug-report #27 is having.
