### ISSUE TITLE
Robot status event are not regularly updated

### ISSUE THREAD

**Issue by DRazumovskiy** [andreypopov/node-red-contrib-miio-roborock#27]
After the last update miio-roborock-event stopped sending events. Polling interval was changed from 30 to 10 seconds making no difference. Events are sent on flow start and after changing and deploying the configuration, for example after changing the polling interval.

**Hardware / Software**

- Raspberry 3
- Node Red 1.2.9
- nodejs 10.24.0
- node-red-contrib-miio-roborock 2.1.2

**Comment by andreypopov** [comment]
update nodejs to 12 ver

**Comment by DRazumovskiy** [comment]
- Update nodejs to v12.21.0
- Removed node-red-contrib-miio-roborock
- Installed node-red-contrib-miio-roborock with npm install

Same results. Events are not received by event node. Logs are clean. There's a strange artefact with nodes visualization in manage pallet. Probaby unrelated to the case

![image](https://user-images.githubusercontent.com/13840421/110661058-79aebd00-81c4-11eb-9710-8855f6195eb4.png)

**Comment by andreypopov** [comment]
what is the model of vacuum? Did it work previously?

**Comment by andreypopov** [comment]
please, check node-red-contrib-miio-roborock@2.1.3

**Comment by DRazumovskiy** [comment]
Updated to 2.1.3, restarted Node Red, but unfortunatelly events are still not generated by the event node. Polling interval set to 30 seconds.

Roborock model is S5 and events were properly generated before the last few updates (before last Saturday, when I upgraded the plugin).

### Additional details
It's not only the problems with missing events, but also the data on request is not correct. When I send an msg.payload = timestamp to the input of **miio-roborock-event** node it immediately responds with an array, but the data in this array is obsolete: i.e. the robot is paused in the center of the room, but the data in arrays says it's still charging.

Command node works totally fine as it was before the update

**Comment by andreypopov** [comment]
I dont have such issue, yesterday I tested event the whole day, everything was nice.
I have no idea. 

Try older versions of node-red-contrib-miio-roborock. Search for the last working version.

**Comment by andreypopov** [comment]
fixed in + node-red-contrib-miio-roborock@2.2.0

**Comment by S474N** [comment]
Upgraded today to node-red-contrib-miio-roborock 2.1.3. Before this on version 2.1.2 was everything OK, now this reply:
![image](https://user-images.githubusercontent.com/16512337/111076312-20a89700-84ec-11eb-8771-bf7ca4c40228.png)


(NodeRED 1.2.9, Node.js 12.20.1, RPi 4B, dockerized https://hub.docker.com/r/nodered/node-red/ )

**Comment by andreypopov** [comment]
try 2.2.0

**Comment by S474N** [comment]
OK and where is located?

**Comment by S474N** [comment]
`Manage palette` don't have it :(

**Comment by S474N** [comment]
OK, installed 2.2.0, there is only info about "Charging" under first node (+ Battery) and Room ID mapping, but nothing else. Same error as above.

**Comment by andreypopov** [comment]
Please check + node-red-contrib-miio-roborock@2.2.2, I observed two days. this version is very stable.

**Comment by DRazumovskiy** [comment]
Hi Andrey, thank you for fixing this issue. I've upgraded today and events are sent as configured.
