### ISSUE TITLE
Command send error

### ISSUE THREAD

**Issue by Diddlik** [andreypopov/node-red-contrib-miio-roborock#3]
** Describe issue **
No matter what workflow I do get this error:

**20.11.2019, 22:53:07node: 53a52878.b76968
msg : error
"TypeError: Cannot read property 'call' of undefined"**

** Your flow here **
`[
    {
        "id": "a21fc7f4.d035a",
        "type": "debug",
        "z": "9d1ea663.559318",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1110,
        "y": 1100,
        "wires": []
    },
    {
        "id": "53a52878.b76968",
        "type": "miio-roborock-command",
        "z": "9d1ea663.559318",
        "name": "",
        "server": "1e9004e.21f587b",
        "command_name": "ⓘ Get status",
        "command": "get_status",
        "commandType": "vacuum_cmd",
        "payload": "10",
        "payloadType": "str",
        "coordinates": "",
        "fan_speed": "",
        "homekit_stop_to_dock": true,
        "x": 910,
        "y": 1100,
        "wires": [
            [
                "a21fc7f4.d035a"
            ]
        ]
    },
    {
        "id": "c550df90.366d7",
        "type": "inject",
        "z": "9d1ea663.559318",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "num",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 720,
        "y": 1100,
        "wires": [
            [
                "53a52878.b76968"
            ]
        ]
    },
    {
        "id": "1e9004e.21f587b",
        "type": "miio-roborock-server",
        "z": "",
        "name": "Ivar",
        "ip": "192.168.1.115",
        "token": "3970474a486d333xxxxxxxxxxxxxxxxx",
        "polling": "10"
    }
]`

** Screens / Logs **
![grafik](https://user-images.githubusercontent.com/6010713/69281675-fe00b980-0be8-11ea-927f-8719793b8e89.png)

** Hardware / Software **
  - CCU3 (Homematic IP CCU3)   
  - node-red-contrib-miio-roborock 1.1.2

**Comment by andreypopov** [comment]
Hi, I need more info, file and line number.
Right now I dont have roborock, so it is impossible to check.
Try to re-add Get Status node.

**Comment by Diddlik** [comment]
After some testing it turned out that the node-red was not ok. A restart has helped.

Thank you!!!

**Comment by Fastigit** [comment]
I have the same problem that you had. But restarting/upgrading Node Red did not help.
every 20 seconds the debug window prints:
Miio Roborock Error: Could not connect to device, token might be wrong
If i try to send a command to the Roborock i get:
TypeError: Cannot read property 'call' of undefined
I'm shure, that the token is correct as if I'm using the same token in FHEM to control the Roborock it works fine

**Comment by Boh1** [comment]
I have the same issue. 

Automations work fine, I just keep getting this error. And I'm not sure which exact node is causing this. Even the Catch node won't filter them out.
