### ISSUE TITLE
"Miio Roborock Error: Could not connect to device, token might be wrong"

### ISSUE THREAD

**Issue by antti365** [andreypopov/node-red-contrib-miio-roborock#32]
** Describe issue **
"Miio Roborock Error: Could not connect to device, token might be wrong"

![Снимок экрана 2021-04-07 в 11 32 12](https://user-images.githubusercontent.com/6865425/113835816-f8cbec80-9794-11eb-986a-d703189ddccc.jpg)

Hi, every day at the same time I see the same message on the "debug" tab in Node red, it is repeated 4 times at 03:58 - "Miio Roborock Error: Could not connect to device, token might be wrong". The token is there, it is configured correctly and the node is working perfectly - why do these messages appear and how can they be removed?

** Hardware / Software **
  - raspberry 3
  - version of Node red 1.2.9
  - version node-red-contrib-miio-roborock 2.2.2

**Comment by andreypopov** [comment]
it is ok, vacuum reconnects to wifi
(possible reason: your gateway updates and then restart services)

**Comment by antti365** [comment]
Ok, I see, thanks.
