### ISSUE TITLE
Dust status

### ISSUE THREAD

**Issue by Donni1966** [andreypopov/node-red-contrib-miio-roborock#33]
Hello, 
I am absolutely thrilled with the Node-red palette. High praise. 
now I have a question, I would like to determine or display what is the status of the dust container. Unfortunately I have not found anything that gives an indication when the container is missing or full. 

am i doing something wrong?

**Comment by fromCologne** [comment]
Here you can find all commands the xiaomi vacuums know.
[https://github.com/marcelrv/XiaomiRobotVacuumProtocol](url)

Look at GET_STATUS. These data you will get by the node miio-roborock-event. And the "Status Code" will give you 254 = bin full

**Comment by Donni1966** [comment]
thx a lot - I will check it.
