### ISSUE TITLE
Roborock S7

### ISSUE THREAD

**Issue by fromCologne** [andreypopov/node-red-contrib-miio-roborock#34]
Hi Andrey,

I tested with Roborock S7. In the config tab of the node is no dropdown for commands. The dropdown for voice pack is empty. Some commands of the sample flow works, some not.
If I can support the development with test let me know.

Ingo

**Comment by andreypopov** [comment]
what is the version of node-red? nodejs ?

Feel free to Pull request any improvements for S7

**Comment by fromCologne** [comment]
Problem with node-red 1.3.5 (Docker), node-red-contrib-miio-roborock 2.2.4

I upgraded to node red 2.0.5 and now there is the download list for commands. Voice pack disappeared.
Now I will test the commands.

TNX for your help.

**Comment by andreypopov** [comment]
There are no voicepacks, because I don't know which are compatible with s7.

**Comment by fromCologne** [comment]
Hello Andrey,
i try to download a map from xiaomi cloud with command "get_map_v1" and i get a response from the server. But how i have to format my http-request to download the map? Please do you have an example? 
Regards
Ingo
