### ISSUE TITLE
command list not scrollable

### ISSUE THREAD

**Issue by andrasg** [andreypopov/node-red-contrib-miio-roborock#4]
** Describe issue **
The commands list is larger than the screen. Lot of commands are not selectable. See screenshot

** Your flow here **
_not flow specific_

** Screens / Logs **
<img width="352" alt="image" src="https://user-images.githubusercontent.com/10730249/70556926-1f1e4f80-1b82-11ea-9a6c-83ed9ff6d87d.png">

** Hardware / Software **
- doesn't work on Safari or Edge (Chromium)
- raspberry 4   
- version of deconz gateway: [2.05.66 / 16/06/2019] 
- version of node-red-contrib-deconz: [0.10]

**Comment by andreypopov** [comment]
node-red version? it is node-red's common UI component

**Comment by andrasg** [comment]
Seems to be fixed in Nodered version `1.0.5`. Thanks!
