### ISSUE TITLE
Handshake timeout - different VLANs

### ISSUE THREAD

**Issue by Drahos-X** [andreypopov/node-red-contrib-miio-roborock#47]
I am getting "Miio Roborock Error: Could not connect to device, handshake timeout".

Node-red and Roborock Q7 are on a different VLANs - this is perhaps the reason. 

Node-red "Get Token" button works fine and returns the correct token (also verified by other methods).
IP address is correct and reachable from Raspberry Pi running Node-red.

Can you help? What could I try to make it work?

**Comment by Drahos-X** [comment]
The issue is solved by adding this to the _uck-config.gateway_ on the UniFi Controller (UCK):

	"nat": {
		"rule": {
			"5000": {
				"description": "MASQ requests to Roborock [IP_ADDRESS]",
				"destination": {
					"address": "IP_ADDRESS"
				},
				"outbound-interface": "eth0.10",
				"protocol": "tcp_udp",
				"type": "masquerade"
			}
		}
	}

_Replace IP_ADDRESS with Roborock IP address; replace eth0.10 with your VLAN with Roborock._

The root cause is the source address in the UDP packet. The device won’t respond to the request, in case the source address of the UDP packet doesn’t belong to the subnet of the device itself.

Useful info:
https://python-miio.readthedocs.io/en/latest/troubleshooting.html
https://help.ui.com/hc/en-us/articles/204976494-EdgeRouter-Source-NAT-and-Masquerade
https://help.ui.com/hc/en-us/articles/215458888-UniFi-USG-Advanced-Configuration-Using-config-gateway-json
https://jsonlint.com/

Do not forget to update permisions for the config file (if creating a new one):
ssh root@_UCK_
cd /srv/unifi/data/sites/default/
chown unifi:unifi config.gateway.json
chmod 640 config.gateway.json

**Comment by egeu5** [comment]
Thank you for this hint! Have the same problem with different VLANs. 

My solution was to add another virtual network interface on the NodeRed virtual machine. Then I put the network interface in my IoT-Vlan by tagging it with its vlan id. Reboot the container inside the vm. Done!
