### ISSUE TITLE
Change Map function

### ISSUE THREAD

**Issue by tromanski** [andreypopov/node-red-contrib-miio-roborock#57]
Dear all,

I have several maps set up in the xiaomi app for all flors. Is it possible to change the map in the node? If not, would it be possible to implement such a function? Or is there already a workaround?

A flow could look like this:
select to clean 2nd floor --> roborock moves from dock to the stairs in 1st floor --> changes the map to 2nd floor --> roborock is moved by hand to 2nd floor--> press start manually on the robock --> roborock starts work --> comes back to the start point --> changes map to 1st floor --> move to 1st floor by hand --> press start again on roborock--> roborock goes back to station

Would be great to have this function.

Best regards

**Comment by MarkResting** [comment]
Hi, 
I have the same problem to send the roborock in the correct room.
I have 2 floors and the room numbers looks like the same on both floors, and i can't send the roborock to the first room, when the map is not set correct. If i change the map in the app it's working fine.

So really thanks a lot for this nice plugin and i hope that the map-selection is doable.

Thx and kind regards,
Mark

**Comment by tromanski** [comment]
@MarkResting: The solution is here [(LINK).](https://github.com/andreypopov/node-red-contrib-miio-roborock/issues/40) But for me map 0 also didn´t work but everything above (1,2,3, etc.) works. So you can make a new map for "map 0" e.g. "map 2" and then you can call it. Just don´t delete "map 0"

**Comment by tromanski** [comment]
see above
