### ISSUE TITLE
no connection to the vacuum after restarting nodered

### ISSUE THREAD

**Issue by gnome4711** [andreypopov/node-red-contrib-miio-roborock#6]
Hi there!
Í own 2 Xiaomi Vacuums (1.gen). Both are running well within nodered (on Rpi3).
The problem is that 8 out of 10 times after i had to restart nodered (service nodered restart) the devices aren't found anymore ("TypeError: Cannot read property 'call' of undefined").

The only solution ist to delete the  configuration-nodes, make a deploy and make knew configs (add a new roborock-server).

Any ideas?

** Your flow here **
Export your flow in json 

** Screens / Logs **

** Hardware / Software **
  - raspberry 4   
  - version of deconz gateway: [2.05.66 / 16/06/2019] 
  - version of node-red-contrib-deconz: [0.10]

**Comment by andreypopov** [comment]
can you give full log with error line number and file?

as far as I dont own vacuum it is pretty hard to fix

**Comment by gnome4711** [comment]
here is a part of the console log:

What file could I post ?

6 Jan 12:05:42 - [error] [miio-roborock-command:d7e371fe.49c7b8] TypeError: Cannot read property 'call' of undefined
(node:19517) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of undefined
    at /home/pi/.node-red/node_modules/node-red-contrib-miio-roborock/nodes/server.js:99:37
    at new Promise (<anonymous>)
    at ServerNode.getStatus (/home/pi/.node-red/node_modules/node-red-contrib-miio-roborock/nodes/server.js:96:20)
    at Timeout._onTimeout (/home/pi/.node-red/node_modules/node-red-contrib-miio-roborock/nodes/server.js:27:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:19517) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 63)
(node:19517) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of undefined
    at /home/pi/.node-red/node_modules/node-red-contrib-miio-roborock/nodes/server.js:99:37
    at new Promise (<anonymous>)
    at ServerNode.getStatus (/home/pi/.node-red/node_modules/node-red-contrib-miio-roborock/nodes/server.js:96:20)
    at Timeout._onTimeout (/home/pi/.node-red/node_modules/node-red-contrib-miio-roborock/nodes/server.js:27:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:19517) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 64)

**Comment by andreypopov** [comment]
bug confimed. I dont have vacuum right now but I will try to fix it

**Comment by andreypopov** [comment]
> Hi there!
> Í own 2 Xiaomi Vacuums (1.gen). Both are running well within nodered (on Rpi3).
> The problem is that 8 out of 10 times after i had to restart nodered (service nodered restart) the devices aren't found anymore ("TypeError: Cannot read property 'call' of undefined").
> 
> The only solution ist to delete the configuration-nodes, make a deploy and make knew configs (add a new roborock-server).
> 
> Any ideas?
> 
> ** Your flow here **
> Export your flow in json
> 
> ** Screens / Logs **
> 
> ** Hardware / Software **
>   - raspberry 4  
> 
> * version of deconz gateway: [2.05.66 / 16/06/2019]
>     - version of node-red-contrib-deconz: [0.10]

+ node-red-contrib-miio-roborock@1.1.3
try  even pi reboot
