### ISSUE TITLE
Rooms cleaning

### ISSUE THREAD

**Issue by nightmare04** [andreypopov/node-red-contrib-miio-roborock#7]
Add rooms cleaning by rooms id's

**Comment by andreypopov** [comment]
what do you mean?  give me more details, please
model of your vacuum

**Comment by nightmare04** [comment]
Ладно, в английском не силен, но думаю поймете :)
В общем хотел сказать чтобы добавили запуск уборки не по комнатам, а по номерам комнат в пылесосах где это возможно, например в m1s точно есть, в том же адаптере для iobrokera это реализовано.

**Comment by L1brTy** [comment]
HI, 

the new firmware for the S5 model supports seperated rooms.

In the app i can chose one or several rooms and strat cleaning.

is it possible to start cleaning a selected room via node ?



![roborockRooms](https://user-images.githubusercontent.com/57085514/76188817-6647cb00-61d9-11ea-9c11-73de0eb686eb.png)

**Comment by andreypopov** [comment]
I use https://github.com/aholstenson/miio library, it doesn't support it.
I will buy 2 vacuums in 4-5months and will upgrade functionality.
now I dont have vaccum, cant test

**Comment by damsh** [comment]
To start room cleaning you need to issue app_segment_clean[x] command to the vacuum cleaner, where x - room number.

**Comment by andreypopov** [comment]
does it work?

**Comment by damsh** [comment]
Yes. I use it in openhab vacuum binding. It's slightly difficult to find room numbers, because my S50 does not support get_room_mapping[] command, but using tests I found them all. 
Here is the list of commands: https://github.com/marcelrv/XiaomiRobotVacuumProtocol

**Comment by b0c1** [comment]
+1 to room cleaning...

**Comment by andreypopov** [comment]
+ node-red-contrib-miio-roborock@1.1.4

try, you are always able to set ANY command manually with my plugin

**Comment by andreypopov** [comment]
can someone check this update?

**Comment by scomans** [comment]
Seems to work fine even tho it doesn't show the translations correctly:
![image](https://user-images.githubusercontent.com/631504/79684278-4a036900-8230-11ea-85b6-9ed3b9a75534.png)
Do you know any way to get the segment IDs without trying them 1 by 1?

**Comment by pawelhome** [comment]
I have this error: "Miio Roborock error on command 'app_segment_clean': Method `app_segment_clean` is not supported"

**Comment by andreypopov** [comment]
what is vacuum model?

**Comment by pawelhome** [comment]
S50, I tried with mirobo python app, and the raw command "app_segment_clean" works.

Stop and resume seems to work, the respond from the vacuum is "ok"

**Comment by antti365** [comment]
Hi, my apartment is divided into five segments, I managed to pick 4 out of 5 segments, 16, 17, 18, 19 - S50 starts to clean them safely, and in the application Mi Home that room is highlighted, which is being cleaned. The fifth segment could not be found by exhaustive search. Roborock: event node returns - state: "unknown-18" while the vacuum clean a segment. Is it possible to add get_room_mapping [] command, what if it works for me?

**Comment by andreypopov** [comment]
You can use any command! 
![2020-04-26_20-35-47](https://user-images.githubusercontent.com/1624839/80314996-8a00b800-87fd-11ea-8019-b360324ad12a.png)

**Comment by antti365** [comment]
Yes, thanks, I didn’t understand. This command didn’t work for me (get_room_mapping), iterated over the last segment (number 2), by the way this is the only room that the Mi Home program recognized after drawing a map of the entire apartment. All other rooms were identified through "zone editing" and received double-digit numbers ...

**Comment by tomSmartHome** [comment]
> You can use any command!
> ![2020-04-26_20-35-47](https://user-images.githubusercontent.com/1624839/80314996-8a00b800-87fd-11ea-8019-b360324ad12a.png)

I'm trying this approach, but don't know how to pass the command params. It has to be an array like here: https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/segment_clean.md#example

I keep getting "Miio Roborock error on command 'app_segment_clean': Param size error"

**Comment by Mathyass** [comment]
> S50, I tried with mirobo python app, and the raw command "app_segment_clean" works.
> 
> Stop and resume seems to work, the respond from the vacuum is "ok"

Hi i have the same problem ... Please Did you find how to fix it ?

**Comment by Mathyass** [comment]
What am i doing wrong ? i hope everything i have correct but nodered returns 
"Miio Roborock error on command 'app_segment_clean': Method `app_segment_clean` is not supported"
But if i try from command line 
miio protocol call <IP adress> app_segment_clean [11,12]
something happened and robot go to clean. The second is how to obtain correct numbers of rooms but its another story...

I have Roborock S6

Thnx for any idea...

**Comment by SimplyRyan** [comment]
> 
> 
> What am i doing wrong ? i hope everything i have correct but nodered returns
> "Miio Roborock error on command 'app_segment_clean': Method `app_segment_clean` is not supported"
> But if i try from command line
> miio protocol call app_segment_clean [11,12]
> something happened and robot go to clean. The second is how to obtain correct numbers of rooms but its another story...
> 
> I have Roborock S6
> 
> Thnx for any idea...

Inject a JSON payload of your room e.g. `[16]` into a command node of `app_segment_clean` and it should work. 

Tested on a S5 using the latest firmware which supports rooms. I wasen't able to get this to work at all in just a command node alone. You should be able to chain rooms as well e.g. `[16,17]`.

![command_flow](https://user-images.githubusercontent.com/5630595/83389514-aebb0180-a433-11ea-84a6-d3c4f23f2b11.png)

**Comment by SimplyRyan** [comment]
> 
> 
> Hi, my apartment is divided into five segments, I managed to pick 4 out of 5 segments, 16, 17, 18, 19 - S50 starts to clean them safely, and in the application Mi Home that room is highlighted, which is being cleaned. The fifth segment could not be found by exhaustive search. Roborock: event node returns - state: "unknown-18" while the vacuum clean a segment. Is it possible to add get_room_mapping [] command, what if it works for me?

On my S5 `unknown-18` is comes up for all room cleans, cosmetic in my case but I created a PR to resolve it. https://github.com/andreypopov/node-red-contrib-miio-roborock/pull/13

Not related to your segment rages but I wanted to just point this out.

**Comment by ferminvz** [comment]
Hi SimplyRyan! Can you show how to configure the inject node y and the robobock command node? I think Im near but can't make it work ( roborock S6 )

**Comment by SimplyRyan** [comment]
Yeah, load the following example and it should be clear.

```
[
    {
        "id": "e9b8bc45.8b0d8",
        "type": "tab",
        "label": "Flow 3",
        "disabled": false,
        "info": ""
    },
    {
        "id": "c03a7e42.da79b8",
        "type": "miio-roborock-command",
        "z": "e9b8bc45.8b0d8",
        "name": "Segment Clean",
        "server": "fb5f262a.1dd2f8",
        "command_name": null,
        "command": "app_segment_clean",
        "commandType": "str",
        "payload": "payload",
        "payloadType": "msg",
        "coordinates": "",
        "fan_speed": 100,
        "voice_pack": null,
        "homekit_stop_to_dock": false,
        "x": 520,
        "y": 180,
        "wires": [
            []
        ]
    },
    {
        "id": "a31559e0.69fc1",
        "type": "inject",
        "z": "e9b8bc45.8b0d8",
        "name": "Room y",
        "topic": "",
        "payload": "[16]",
        "payloadType": "json",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 330,
        "y": 180,
        "wires": [
            [
                "c03a7e42.da79b8"
            ]
        ]
    },
    {
        "id": "fb5f262a.1dd2f8",
        "type": "miio-roborock-server",
        "z": "",
        "name": "roborock",
        "ip": "1.1.1.1",
        "token": "000000000000000000000000",
        "polling": "10"
    }
]
```

**Comment by ferminvz** [comment]
> Yeah, load the following example and it should be clear.
> 
> ```
> [
>     {
>         "id": "e9b8bc45.8b0d8",
>         "type": "tab",
>         "label": "Flow 3",
>         "disabled": false,
>         "info": ""
>     },
>     {
>         "id": "c03a7e42.da79b8",
>         "type": "miio-roborock-command",
>         "z": "e9b8bc45.8b0d8",
>         "name": "Segment Clean",
>         "server": "fb5f262a.1dd2f8",
>         "command_name": null,
>         "command": "app_segment_clean",
>         "commandType": "str",
>         "payload": "payload",
>         "payloadType": "msg",
>         "coordinates": "",
>         "fan_speed": 100,
>         "voice_pack": null,
>         "homekit_stop_to_dock": false,
>         "x": 520,
>         "y": 180,
>         "wires": [
>             []
>         ]
>     },
>     {
>         "id": "a31559e0.69fc1",
>         "type": "inject",
>         "z": "e9b8bc45.8b0d8",
>         "name": "Room y",
>         "topic": "",
>         "payload": "[16]",
>         "payloadType": "json",
>         "repeat": "",
>         "crontab": "",
>         "once": false,
>         "onceDelay": 0.1,
>         "x": 330,
>         "y": 180,
>         "wires": [
>             [
>                 "c03a7e42.da79b8"
>             ]
>         ]
>     },
>     {
>         "id": "fb5f262a.1dd2f8",
>         "type": "miio-roborock-server",
>         "z": "",
>         "name": "roborock",
>         "ip": "1.1.1.1",
>         "token": "000000000000000000000000",
>         "polling": "10"
>     }
> ]
> ```

thanks a lot! that work!

**Comment by SimplyRyan** [comment]
@andreypopov you can probably close this issue now.

**Comment by andreypopov** [comment]
![2020-09-04_13-03-51](https://user-images.githubusercontent.com/1624839/92227548-1b202380-eeaf-11ea-9cce-6975078c09da.png)
