### ISSUE TITLE
Send to coordinates" doesn't work

### ISSUE THREAD

**Issue by Bundeshorst** [andreypopov/node-red-contrib-miio-roborock#8]
**Describe issue** 
Command "Send to coordinates" doesn't work. I have just edit your example flow.
There is only an error wich means translated from german "node doesn't exist"

 **Your flow here** 

[{"id":"7e9bd56d.f6b694","type":"miio-roborock-command","z":"c7488f0a.fc4e38","name":"","server":"bcbfdd12.9e4648","command_name":"Send to coordinates","command":"app_goto_target","commandType":"vacuum_cmd","payload":"payload","payloadType":"msg","coordinates":"","fan_speed":"","homekit_stop_to_dock":true,"x":1820,"y":80,"wires":[["7dc23e17.def3a8"]]},{"id":"69cbc8d4.8c6dc","type":"inject","z":"c7488f0a.fc4e38","name":"zum Müll","topic":"","payload":"[30900,27800]","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1640,"y":80,"wires":[["7e9bd56d.f6b694"]]},{"id":"bcbfdd12.9e4648","type":"miio-roborock-server","z":"","name":"robot","ip":"192.xx.xx.26","token":"46xxxxxxxxxxxxxxxxx4f","polling":"10"}]

 **Hardware / Software** 
  - raspberry 3  
  - 1.0.2: Maintenance Release

**Comment by andreypopov** [comment]
what is the model of your vacuum cleaner?'

**Comment by Bundeshorst** [comment]
Roborock S50

I found the problem. I had to delete all unused HomeKit-configuration-nodes from the samples. Then it works.
