### ISSUE TITLE
Event Types in event Node configuration empty/disabled therefor not selectable

### ISSUE THREAD

**Issue by paede81** [andreypopov/node-red-contrib-miio-roborock#9]
** Describe issue **
I try to setup the event node for the first time but I can't open the dropdown to select the Event Types.

HTML source code of the UI element:
`<div class="ms-parent s-width" style="width: 320px;"><button type="button" class="ms-choice disabled">
      <span class="placeholder"></span>
      <div></div>
      </button><div class="ms-drop bottom" style="width: 320px;">
        <div class="ms-search">
          <input type="text" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" placeholder="Filter events">
        </div>
      <ul style="max-height: 300px;"><li class="ms-no-results">No matches found</li></ul></div></div>`

** Screens / Logs **
![image](https://user-images.githubusercontent.com/19265431/82822004-5f118e80-9ea5-11ea-8093-458c2e711c57.png)

** Hardware / Software **
  - raspberry 4

**Comment by paede81** [comment]
Because of that I also did not get any messages on the output (via debug node)

**Comment by TomasDlg** [comment]
Такая же проблема. Из ноды Event перестали лететь сообщения, хотя статус самой ноды меняется.

**Comment by SimplyRyan** [comment]
Ran into the same issue, new install of node red and installed node-red-contrib-miio-roborock via pallete. Did some regression testing and found the following:

**Working - Events Type is populated**
- node-red-contrib-miio-roborock-1.1.4 
- node-red-contrib-miio-roborock-1.1.3 

**Not Working - Events Type is NOT populated**
- node-red-contrib-miio-roborock-1.1.6
- node-red-contrib-miio-roborock-master 

Tested on docker node-red:latest (1.0.6).

**Comment by paede81** [comment]
@andreypopov : Any chance/plan to fixe the issue?

**Comment by andreypopov** [comment]
did you try 1.1.7 ?
I dont have roborock right now, so I can't test.
I plan to buy it in 3 months.

**Comment by paede81** [comment]
Yes tried it with 1.1.7, still not possible to select event types
@SimplyRyan: Can you confirm?

**Comment by andreypopov** [comment]
> Yes tried it with 1.1.7, still not possible to select event types
> @SimplyRyan: Can you confirm?

Can you write me ? We will fix it fast 
skype: dunkle21
telegram: @popov1988

**Comment by paede81** [comment]
Issues fixed in version 1.1.8. Thanks a lot for the great support!

**Comment by SimplyRyan** [comment]
Just updated to 1.1.8 and can confirm its working fine for me as well. Thank you @andreypopov
